name: checkov-plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        required: true
        default: "development"
      region:
        description: "region"
        required: true
        default: "eu-central-1"
      stack:
        description: "terragrunt stack"
        required: true
        default: "vpc"

jobs:
  checkov-plan:
    runs-on: self-hosted
    steps:
      - name: check
        run: |
          echo "environment ${{ github.event.inputs.environment }}"
          echo "region ${{ github.event.inputs.region }}"
          echo "stack ${{ github.event.inputs.stack }}"
