name: checkov-plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        required: true
        default: "development"
      region:
        description: "region"
        required: true
        default: "eu-central-1"
      stack:
        description: "terragrunt stack"
        required: true
        default: "vpc"

jobs:
  checkov-plan:
    runs-on: gergonullfuga/terragrunt:v1
    steps:
      - name: echo inputs
        run: |
          echo "environment ${{ github.event.inputs.environment }}"
          echo "region ${{ github.event.inputs.region }}"
          echo "stack ${{ github.event.inputs.stack }}"

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::567749996660:role/checkov-role
          aws-region: eu-central-1
          run: aws sts get-caller-identity
