name: checkov-plan

on:
  workflow_dispatch:
    inputs:
      checkSelected:
        description: "run checkov on selected environment"
        required: true
        default: true
        type: boolean

      environment:
        description: "environment"
        required: true
        default: "development"
      region:
        description: "region"
        required: true
        default: "eu-central-1"
      stack:
        description: "terragrunt stack"
        required: true
        default: "vpc"

permissions:
  id-token: write
  contents: read

jobs:
  checkov-plan:
    runs-on: ubuntu-latest
    container:
      image: gergonullfuga/terragrunt:v2.1.0
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: echo inputs
        run: |
          echo "environment ${{ github.event.inputs.environment }}"
          echo "region ${{ github.event.inputs.region }}"
          echo "stack ${{ github.event.inputs.stack }}"

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::567749996660:role/checkov-role
          aws-region: eu-central-1

      - name: check plan
        if: ${{ github.event.inputs.checkSelected == 'true' }}
        run: |
          WORKDIR=infrastructure/live/${{ github.event.inputs.environment }}/${{ github.event.inputs.region }}/${{ github.event.inputs.stack }}
          TERRAGRUNT_CACHE=.terragrunt-stack/vpc/.terragrunt-cache

          terragrunt init --all --working-dir $WORKDIR
          terragrunt plan --all --working-dir $WORKDIR --out tfplan.binary

          BINARY="$(fdfind -H -i tfplan.binary $WORKDIR/$TERRAGRUNT_CACHE)"
          cd ./${BINARY%/*}
          tofu show -json tfplan.binary | jq > tfplan.json

          checkov -f tfplan.json --soft-fail -o github_failed_only | tee -a $GITHUB_STEP_SUMMARY

      - name: check all plan
        if: ${{ github.event.inputs.checkSelected == 'false' }}
        run: |
          #!/bin/bash -eux

          BIN_NAME=tfplan.binary
          JSON_NAME=tfplan.json
          JSON_DIR=json-plans

          convert_bin_to_json() {
          fdfind -HI -t f $BIN_NAME | while read -r FILE; do
            INFRA_DIR=$(pwd)
            cd $(dirname "$FILE")
            tofu show -json $BIN_NAME | jq > $JSON_NAME
            cd $INFRA_DIR
          done
          }

          collect_json() {
          mkdir -p $JSON_DIR
          INDEX=0
          fdfind -HI -t f tfplan.json | while read -r FILE; do
            INDEX=$((INDEX + 1))
            mv "$FILE" "$JSON_DIR/tfplan$INDEX.json"
          done
          }

          cd infrastructure
          terragrunt init --all
          terragrunt plan --all --out $BIN_NAME

          convert_bin_to_json
          collect_json

          checkov -d $JSON_DIR --soft-fail -o github_failed_only >> $GITHUB_STEP_SUMMARY

      - name: check selected policy
        if: ${{ github.event.inputs.checkSelected == 'false' && github.event.inputs.checkPolicy != '' }}
        run: |
          checkov -d infrastructure/json-plans \
          --external-checks-dir ./custom-policies \
          --check ${{ github.event.inputs.checkPolicy }}
