name: checkov-plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        required: true
        default: "development"
      region:
        description: "region"
        required: true
        default: "eu-central-1"
      stack:
        description: "terragrunt stack"
        required: true
        default: "vpc"

permissions:
  id-token: write
  contents: read

jobs:
  checkov-plan:
    runs-on: ubuntu-latest
    container:
      image: gergonullfuga/terragrunt:v2.1.0
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: echo inputs
        run: |
          echo "environment ${{ github.event.inputs.environment }}"
          echo "region ${{ github.event.inputs.region }}"
          echo "stack ${{ github.event.inputs.stack }}"

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::567749996660:role/checkov-role
          aws-region: eu-central-1

      - name: check plan
        run: |
          WORKDIR=infrastructure/live/${{ github.event.inputs.environment }}/${{ github.event.inputs.region }}/${{ github.event.inputs.stack }}

          terragrunt init --all --working-dir $WORKDIR
          terragrunt plan --all --working-dir $WORKDIR --out tfplan.binary

          BINARY="$(fdfind -H -i tfplan.binary $WORKDIR)"
          cd ./${BINARY%/*}
          tofu show -json tfplan.binary | jq > tfplan.json

          checkov -f tfplan.json --soft-fail >> $GITHUB_STEP_SUMMARY
